### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by satyam4484**
check these something cool and  if you would like to join me , check my profile and contact me .

### CODE REVIEW

**Comment by pratikshahake26** [comment]
Nice & Thanks for this idea, also I am following you on GitHub.

**Comment by satyam4484** [comment]
yes i know you follow me , you can do things better , but for now focus only on data structure and algo. if required any help can contact.

**Comment by pratikshahake26** [comment]
Ok, thanks.

**Comment by satyam4484** [comment]
wlc

**Pull request merged**
